### ISSUE TITLE
[Q] SCRIPT=run_gpt.py bash run_multi.sh ?

### ISSUE THREAD

**Issue by flipflop98** [bearpelican/musicautobot#1]
Dear Bearpelican,

What do you mean by "SCRIPT=run_gpt.py bash run_multi.sh" command?
If I use this@midi_generator-master dir, 
$ SCRIPT=run_gpt.py bash run_multi.sh --path data/midi/midi_transcribe_v3_shortdur/ --batch_size 8 --lr .0001 --epochs 5 --save gpt/clc/v3ep50
/home/changhyk/anaconda3/envs/midi/bin/python: can't open file 'run_gpt.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/changhyk/anaconda3/envs/midi/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/changhyk/anaconda3/envs/midi/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/changhyk/anaconda3/envs/midi/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/changhyk/anaconda3/envs/midi/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/changhyk/anaconda3/envs/midi/bin/python', '-u', 'run_gpt.py', '--local_rank=0', '--path', 'data/midi/midi_transcribe_v3_shortdur/', '--batch_size', '8', '--lr', '.0001', '--epochs', '5', '--save', 'gpt/clc/v3ep50']' returned non-zero exit status 2.

Any comment ?
Changhyun

**Comment by bearpelican** [comment]
I just updated the readme to be a little bit more clear. That command should be run inside the 'scripts' folder
